Fix "replace" function to work for regex-y strings
Example of error:

    replace 'Something(' 'Something else'

    rg: regex parse error:
        (?:Something()
        ^
    error: unclosed group

Using a single `\` escape sequence would fix the error but cause a
different error instead; just avoid the need in the first place.